version: '3.8'
services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'   # SMTP
      - '8025:8025'   # Web UI
    environment:
      MP_UI_AUTH: 'false'
      MP_SMTP_AUTH_ACCEPT_ANY: 'true'
      MP_SMTP_AUTH_REQUIRED: 'false'

